### ISSUE TITLE
登陆了教师账号之后啥反应都没有。

### ISSUE THREAD

**Issue by ExerciseBook** [gucong3000/safetree#10]
![20170314064855](https://cloud.githubusercontent.com/assets/6327311/23878431/5417252e-0882-11e7-9e9e-eb11864e63ba.png)

是我的操作方式有问题吗？

**Comment by gucong3000** [comment]
正在处理ing

**Comment by gucong3000** [comment]
修正了，正好今天孩子学校又布置了作业，实测OK了，坐标chengdu

但是用你的账号在中山站点登陆，貌似答题后不会记录成绩，麻烦您试试，在当地正常运行的话请告知我。

信息的输出目前不是很友好，大多数信息都输出再这里了：
![image](https://cloud.githubusercontent.com/assets/1171691/23895924/81c930e2-08e2-11e7-9ff2-6165429e75fd.png)


> 遇到界面无反应可按快捷键`Ctrl+R`

**Comment by ExerciseBook** [comment]
依然不可完成。log显示正常，但是没有提交上答案。我也找不到哪里出问题了


希望增加一个功能：丢一个用户名列表进去即可完成任务。

**Comment by gucong3000** [comment]
找到原因了，计算产生的作业url只适用于成都。本周末改正。将改为从"我的作业"页面抓取作业url

**Comment by gucong3000** [comment]
修好了，可正常完成中山作业了。
