### ISSUE TITLE
最近平台要求强制修改密码，建议取消默认密码

### ISSUE THREAD

**Issue by asg1101** [gucong3000/safetree#116]
如题，现在要求密码必须字母加数字组合，建议取消软件的自带密码，增加自定义密码。
现在软件手动输入密码不能登录，但是从网页登录正常。

**Comment by lalalainCN** [comment]
存在此问题，可以自己修改默认密码解决一下

**Comment by asg1101** [comment]
您能说一下在什么地方修改默认密码吗？我找了一下安装目录，没有找到修改密码的配置文件。还是配置文件在别的地方？

**Comment by lalalainCN** [comment]
我改了源代码啦
不过现在网站好像改版了，又不能用了

**Comment by asg1101** [comment]
基础任务也不能做了吗？

**Comment by ExerciseBook** [comment]
看了一下，这个网站现在的 "观看视频" 貌似修改了判定模式
我也搞不懂是什么情况

**Comment by asg1101** [comment]
好麻烦啊，还想省点劲呢
