### ISSUE TITLE
2019年平安寒假专项活动无法完成

### ISSUE THREAD

**Issue by rainvalley** [gucong3000/safetree#124]
全国中小学生（幼儿）2019年平安寒假专项活动，望更新自动完成功能。

附url：https://huodong.xueanquan.com/2019Winter/2019Winter_test.html
答案见附件
[寒假.docx](https://github.com/gucong3000/safetree/files/2880591/default.docx)
测试账号：chaidahao8461 密码：123456

仍然存在nginx的404
![q2ipl pns1o8t3 l9 ckdq7](https://user-images.githubusercontent.com/26929366/53025506-fb2b3980-349b-11e9-8365-b245b317b657.png)

**Comment by rainvalley** [comment]
当然，我不是很确定每个地方的专题测试题内容都一样。

**Comment by gucong3000** [comment]
我本地未发现此情况，建议下载最新版本试试。
