### ISSUE TITLE
不能完成“119消防专题”

### ISSUE THREAD

**Issue by emma135** [gucong3000/safetree#43]

**Comment by gucong3000** [comment]
@emma135 能否提供一下此专题作业的URL和答案呢？

**Comment by emma135** [comment]
[119消防安全教育专题.docx](https://github.com/gucong3000/safetree/files/1502053/119.docx)

**Comment by gucong3000** [comment]
已添加此专题的自动完成功能。
但是上述docx文档中的题目可能不太完整，有较高概率会导致无法全自动完成。
另：未找到可用的测试账号，此功能并未经过测试。

**Comment by emma135** [comment]
不行
![1](https://user-images.githubusercontent.com/33870516/33374326-a88b0ae0-d540-11e7-8b77-e583b0d8e4b4.png)
https://wenku.baidu.com/view/58e4ff55a200a6c30c22590102020740be1ecd87.html?from=search
上面链接有账号

**Comment by gucong3000** [comment]
问题已修复

**Comment by gucong3000** [comment]
@emma135 觉得好用的话，麻烦点亮星星呗。
