### ISSUE TITLE
成都安全教育平台？

### ISSUE THREAD

**Issue by 2458378521** [gucong3000/safetree#66]
下载软件后，安全教育平台是成都的，想问一下能不能换成承德的？联系QQ2458378521

**Comment by gucong3000** [comment]
直接登陆你的账号即可，会自动跳转到承德

**Comment by 2458378521** [comment]
目前该软件是不是瘫痪了？好像不能使了

**Comment by gucong3000** [comment]
> 目前该软件是不是瘫痪了？好像不能使了

貌似是安全教育平台更换域名造成的问题，软件已针对此问题更新，在成都和海外网络环境下测试正常。
