### ISSUE TITLE
可以看看这里，这里貌似不需要输入验证码，但是登录方式十分诡异

### ISSUE THREAD

**Issue by ExerciseBook** [gucong3000/safetree#8]
http://huodong.safetree.com.cn/Winter2017/2017Winter_family.html#
http://speciallogin.safetree.com.cn/SpecialLoginHandler.asmx?op=SpecialLogin

![20170312220844](https://cloud.githubusercontent.com/assets/6327311/23832508/80ebe642-0770-11e7-8410-e3ea8231fc3d.png)

![e_mp_ f qgn dpp f3uzp](https://cloud.githubusercontent.com/assets/6327311/23832433/e87b8e7c-076e-11e7-8c7c-f24eeb118e2e.jpg)

网页上的登录和我自己的登录根本不是一回事。

**Comment by ExerciseBook** [comment]
搞定这个之后应该可以做批量处理，而不是单独处理，这样更刺激 #滑稽

**Comment by gucong3000** [comment]
非常感谢，自从登陆需要验证码之后，批量操作就没正常过。现在终于好了。
