### ISSUE TITLE
专题活动貌似全线gg

### ISSUE THREAD

**Issue by ExerciseBook** [gucong3000/safetree#82]
rt。 基础作业都正常完成。专题作业全部不行。

**Comment by lalalainCN** [comment]
suzhou.safetree.com.cn
username:daigongxia2560
password:123456
望改进
无法做专题

**Comment by gucong3000** [comment]
![image](https://user-images.githubusercontent.com/1171691/38792233-919693c2-417e-11e8-8e03-7a88f08b53f1.png)

@ExerciseBook 
项目首页特意交代了专题作业不支持，需要针对每个专题专门开发新版本
请提供你的作业网址和账号，否则没法帮你

**Comment by gucong3000** [comment]
@lalalainCN 请给一下具体的作业地址，是不是这两个？
https://zhuanti.xueanquan.com/special/nationeducation2018/index.html
https://zhuanti.xueanquan.com/special/drowning2018/index.html

**Comment by ExerciseBook** [comment]
看来属于特殊专题了。。 因为我看专题页面的ui和以前的很像。。我还以为以前的那套可以直接用。

**Comment by ExerciseBook** [comment]
也就是说@lalalainCN 所说的那两个专题。
