### ISSUE TITLE
功能请求：对未知专题作业提供用户人工录入答案功能。

### ISSUE THREAD

**Issue by smartblaack** [gucong3000/safetree#88]
能不能做一个界面，每一次出新题的时候，自动读取题目，然后我自己确定答案。这样不就不需要那么频繁的更新了嘛。如果能再加上一个地区选择更好。

**Comment by ExerciseBook** [comment]
普通作业的话提交接口很少更新。但是专题作业提交接口基本每次都不一样。程序读网页根人读网页的方法是不一样的。所以很难做到“自动读取题目，匹配答案”这种功能。

另外，并不需要地区选择。因为在登陆的时候会自动匹配地区。 安全树网站的用户中心会告诉软件这个账户属于哪一个地区。

**Comment by smartblaack** [comment]
目前的活动作业flash的小游戏题目怎么办的？

**Comment by ExerciseBook** [comment]
flash？ 不存在的。那个不是flash。

**Comment by ExerciseBook** [comment]
这个分很多种【我最近也没看这个网站了，高三挺忙的】，不过根据这个网站的特性，貌似一般只要玩了就行了。那我们应该可以伪造一次游玩的数据包。大概就这样吧。

**Comment by ExerciseBook** [comment]
应该类似于 普通作业里面的作业答案其实并没有上传到服务器，这个程序只是点了一下“提交”。

**Comment by smartblaack** [comment]
有空了试试

**Comment by ExerciseBook** [comment]
你提交一下你的帐号和密码？然后等@gucong3000 来做？

**Comment by ExerciseBook** [comment]
貌似没啥问题吧。最新的两个专题都完成了。

**Comment by gucong3000** [comment]
> 自动读取题目，然后我自己确定答案

计划下次专题作业过期前开发此功能

> 但是专题作业提交接口基本每次都不一样。程序读网页根人读网页的方法是不一样的。所以很难做到“自动读取题目，匹配答案”这种功能。

这个软件做题优先直接操作DOM，其次才是直接调用API接口。基于DOM的话其实不难，专题作业也很有规律，题目都在dl>dt中，答案都在dl>dd>label中，提交按钮可以这样查找`$("a:contains('提交'), #tijiao")`

> 如果能再加上一个地区选择更好

如@ExerciseBook 所说，地区选择是自动化的，如果做界面，还要考虑网站新增地区，地区的中文名和网址映射等情况，所以暂不考虑。

> 目前的活动作业flash的小游戏题目怎么办的？

除个别专题写了提交游戏的逻辑外外，其他忽略，因为游戏做不做目前不影响教师统计成绩。

> 普通作业里面的作业答案其实并没有上传到服务器，这个程序只是点了一下“提交”

不不不，真的提交了标准答案到服务器。

**Comment by ExerciseBook** [comment]
这么刺激的吗。
我记得最开始的基本作业的答案都是本地判断的。
不过专题作业那个是提交到服务器的。

**Comment by asg1101** [comment]
新的专题又出来了，原来的经过测试，不能检测到，能进行下更新吗？512防震减灾专题。

**Comment by smartblaack** [comment]
防震减灾专题出来了，能不能麻烦更新一下
