### ISSUE TITLE
教师登陆问题

### ISSUE THREAD

**Issue by lalalainCN** [gucong3000/safetree#94]
教师密码无法更改为123456，使用工具就无法正常登陆。
如果将源代码中的密码改为登录密码，登录成功后就无法给学生做题。
希望登录时可以自己输入教师密码的，而不要默认123456

**Comment by ExerciseBook** [comment]
教师登陆是可以选择自己的密码的。 您试一下？

**Comment by lalalainCN** [comment]
我发给您我的账号和密码，可以在网页上登陆，但是无法使用这个工具。改了代码中的密码也能登陆，但是做不了作业。您试一下？
留个邮箱吗.

**Comment by gucong3000** [comment]
点我头像可见邮箱。
